[package]
name = "drawpiletimelapse"
version = "2.2.2-beta.2"
rust-version = "1.66.1"
edition = "2021"

[lib]
crate-type = ["staticlib"]
path = "lib.rs"

[dependencies]
anyhow = "1.0.75"
drawdance = { path = "../../drawdance/rust" }
regex = "1.9.4"
xflags = "0.3.1"
