[package]
name = "dprectool"
version = "2.2.2-beta.5"
rust-version = "1.66.1"
edition = "2021"

[lib]
crate-type = ["staticlib"]
path = "lib.rs"

[dependencies]
anyhow = "1.0.75"
drawdance = { path = "../../drawdance/rust" }
xflags = "0.3.1"
