[package]
name = "drawpile-cli"
version = "0.1.0"
edition = "2018"

[dependencies]
dpcore = { path = "../dpcore" }
dpimpex = { path = "../dpimpex" }
clap = "2.33.0"
image = "0.22.3"
tracing-subscriber = "0.1.6"
tracing = "0.1.5"


