name: "Windows Release Build"

on:
  workflow_dispatch:
    inputs:
      drawdance_repo:
        default: "https://github.com/drawpile/Drawdance.git"
        description: "Where to clone the Drawdance repository from. Unless you're working on a fork, the default should be fine."
        required: true
        type: "string"
      drawdance_branch:
        description: "Which branch of Drawdance to build."
        required: true
        type: "string"

env:
  VCPKG_DEFAULT_BINARY_CACHE: "C:/vcpkg-cache" # vcpkg reads this env

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - run: mkdir C:/vcpkg-cache

      - name: Cache vcpkg deps
        uses: actions/cache@v3
        with:
          path: C:/vcpkg-cache
          key: ${{ runner.os }}-build-vcpkg-deps
          restore-keys: |
            ${{ runner.os }}-build-build-vcpkg-deps-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: "Download Drawdance"
        run: |
          pushd C:/
          git clone -b ${{ inputs.drawdance_branch }} ${{ inputs.drawdance_repo }} drawdance
          popd

      - name: "Build"
        run : |
          pushd pkg/win-msvc/
          ./build-release.ps1 -drawdanceDir C:/drawdance
          popd

      - name: "Package"
        run : |
          pushd pkg/win-msvc/
          ./package.ps1
          popd

      - uses: actions/upload-artifact@v3
        with:
          name: drawpile-win-msvc
          path: |
            pkg/win-msvc/drawpile-win-*.zip
            pkg/win-msvc/drawpile-win-*-setup.exe
